// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMwiCLAPYu0p9PBHaelnQK5U6sPceZkY',
    appId: '1:628556014667:web:584075679c545e7b6e99ce',
    messagingSenderId: '628556014667',
    projectId: 'staffdata-bbd6e',
    authDomain: 'staffdata-bbd6e.firebaseapp.com',
    databaseURL: 'https://staffdata-bbd6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'staffdata-bbd6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQch6Z-D-igLXFQaxAmu1XCXJSmL2-rTU',
    appId: '1:628556014667:android:775d6b7af063410d6e99ce',
    messagingSenderId: '628556014667',
    projectId: 'staffdata-bbd6e',
    databaseURL: 'https://staffdata-bbd6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'staffdata-bbd6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWAQ9ipjGGsZgNhkEnWhGHywcz_PI6yk',
    appId: '1:628556014667:ios:d61280dc1bd890456e99ce',
    messagingSenderId: '628556014667',
    projectId: 'staffdata-bbd6e',
    databaseURL: 'https://staffdata-bbd6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'staffdata-bbd6e.appspot.com',
    iosClientId: '628556014667-f5iemrd8j5k26bkbvksu94pa7dl6d4nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWAQ9ipjGGsZgNhkEnWhGHywcz_PI6yk',
    appId: '1:628556014667:ios:d61280dc1bd890456e99ce',
    messagingSenderId: '628556014667',
    projectId: 'staffdata-bbd6e',
    databaseURL: 'https://staffdata-bbd6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'staffdata-bbd6e.appspot.com',
    iosClientId: '628556014667-f5iemrd8j5k26bkbvksu94pa7dl6d4nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffs',
  );
}
